export const TODOS_FETCH_REQUESTED = 'TODOS_FETCH_REQUESTED'
export const TODOS_FETCH_SUCCEEDED = 'TODOS_FETCH_SUCCEEDED'
export const TODOS_FETCH_FAILED = 'TODOS_FETCH_FAILED'

export const TODO_FETCH_REQUESTED = 'TODO_FETCH_REQUESTED'
export const TODO_FETCH_SUCCEEDED = 'TODO_FETCH_SUCCEEDED'
export const TODO_FETCH_FAILED = 'TODO_FETCH_FAILED'

export const TODO_ADD_REQUESTED = 'TODO_ADD_REQUESTED'
export const TODO_ADD_SUCCEEDED = 'TODO_ADD_SUCCEEDED'
export const TODO_ADD_FAILED = 'TODO_ADD_FAILED'

export const TODO_UPDATE_REQUESTED = 'TODO_UPDATE_REQUESTED'
export const TODO_UPDATE_SUCCEEDED = 'TODO_UPDATE_SUCCEEDED'
export const TODO_UPDATE_FAILED = 'TODO_UPDATE_FAILED'

export const TODO_DELETE_REQUESTED = 'TODO_DELETE_REQUESTED'
export const TODO_DELETE_SUCCEEDED = 'TODO_DELETE_SUCCEEDED'
export const TODO_DELETE_FAILED = 'TODO_DELETE_FAILED'

export const DELETE_ALERT_TEXT = 'DELETE_ALERT_TEXT'